- hosts: prometheus-data
  gather_facts: no
  remote_user: "{{ adhoc_remote_user }}"
  become: yes
  become_method: sudo
  tasks:
    - name: prometheus-privileges
      file:
       path: "{{ prometheus.datapath }}/{{ item }}"
       state: directory
       mode: 0777
      with_items:
        - "prometheus"
        - "grafana"
  tags:
   - prometheus


- hosts: prometheus
  gather_facts: no
  remote_user: "{{ adhoc_remote_user }}"
  become: yes
  become_method: sudo
  roles:
    - prometheus
  tags:
    - prometheus
