kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
data:
  config.yml: |-
    global:
      resolve_timeout: 2m
      smtp_smarthost: 'smtp.qiye.163.com:587'
      smtp_from: 'prometheus@growingio.com'
      smtp_auth_username: 'noreply@growingio.com'
      smtp_auth_password: 'gGEP4JhfC2y68xnQ'
      smtp_require_tls: true
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'send_to_dingding_webhook'
      routes:
      - match:
          alertname: NodeMemoryUsage
        receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
        - to: 'sre@growingio.com'
          auth_identity: 'LOGIN'

    - name: "send_to_dingding_webhook"
      webhook_configs:
        - send_resolved: true
          url: http://127.0.0.1:8060/dingtalk/webhook1/send
